[theme]
primaryColor = "#4C5C78"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
